### ISSUE TITLE
Is there an ETA for approval/inclusion by the ledgerHQ folks...

### ISSUE THREAD

**Issue by mrose17** [handshake-org/ledger-app-hns#5]
...so we can use ledger live to put the app on our ledger nano devices?

thanks!

/mtr

**Comment by pinheadmz** [comment]
You will have to ask Ledger! And tell all your friends to ask them too! We are just waiting :-(

**Comment by mrose17** [comment]
https://ledger-dev.slack.com/archives/C2D012G7Q/p1584108175146200

also, thanks for thinking that i have friends, that's very kind of you! (-;

**Comment by pinheadmz** [comment]
The HNS app is now available in dev mode: https://gist.github.com/pinheadmz/500df1a882399fd5c41543739c95d13e

and pending security audit (https://github.com/LedgerHQ/app-handshake/pull/4) will soon be available in public mode.

I'm closing this issue because "no there is no ETA" but just follow the ledger PR I linked above and stay tuned, hopefully we are less than 45 days away from public mode.
